### PR TITLE
Proofread and update espup installation instructions

### PR DESCRIPTION
**Pull request by Nukesor**
Hi :)

I just went through the docs and fixed a number of grammar issues and markdown lint issues.

While at it, I also removed the outdated espup section on the esp-idf installation note

### CODE REVIEW

**Comment by Nukesor** [comment]
Damn @SergioGasquez. You were a tad faster :D

I should've refreshed my pull request tab before opening a new PR.

**Comment by Nukesor** [comment]
I reverted all changes in the installation section to prevent any conflicts with your PR.

**Review by SergioGasquez — APPROVED** [review]
Hi @Nukesor! 

Thanks for proofreading the book and fixing so many details. We are currently working on a big improvement of the book(#59)  but I still see a lot of value in merging this PR.

**Comment by Nukesor** [comment]
I really don't mind, if you're going to close this MR. No harm done :)

Those really only are a few issues that were noticed by me/my grammar checker and the markdown linter.

**Comment by SergioGasquez** [comment]
IMHO merging it does not do any harm and cleans it while we work on the `overhaul`. That said what I think is important is to avoid those errors on the `overhaul` branch, so I'll check it

**Pull request merged**
